name: 7. Create a Sprint Review Closure Report
description: Sprint Review
title: "[Sprint Review]: "
labels: ["Story"]
projects: ["audax-io/84"]
assignees:
  - AASH08
body:
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Description"
    validations:
      required: false
  - type: textarea
    id: List of Items included
    attributes:
      label: List of Items included
      description: List of Items included
      placeholder: List of Items included
      value: "List of Items included"
    validations:
      required: false
  - type: checkboxes
    id: Tasks
    attributes:
      label: Tasks
      description: Tasks
      options:
        - label: Unit test evidence
        - label: Integration Test Evidence
        - label: Code Security Evidence
        - label: Functional QA auto and manual evidence
          required: false
