name: Defect
description: Defect
title: "[Summary]: "
labels: ["UAT Defect", "Productionn Incident"]
projects: ["Test Project2"]
assignees:
  - AASH08
body:
  - type: input
    id: affect-version
    attributes:
      label: affect version
      description: affect version
      placeholder: ex. v.5.5.release6
    validations:
      required: true
  - type: dropdown
    id: Priority
    attributes:
      label: Priority
      description: Priority
      options:
        - Critical
        - High
        - Medium
        - Low
      default: 0
    validations:
      required: true
  - type: dropdown
    id: Severity
    attributes:
      label: Severity
      description: Severity
      options:
        - Critical
        - High
        - Medium
        - Low
      default: 0
    validations:
      required: true
  - type: dropdown
    id: Environment
    attributes:
      label: Environment
      description: What environment was the defect detected?
      options:
        - UAT
        - Production
      default: 0
    validations:
      required: true
  - type: dropdown
    id: Country
    attributes:
      label: Country
      description: Country
      options:
        - ID
        - MY
      default: 0
    validations:
      required: true      
  - type: dropdown
    id: Partner
    attributes:
      label: Partner
      description: What environment was the defect detected?
      options:
        - Buka
        - Sociolla
        - TNGD
      default: 0
    validations:
      required: true
  - type: dropdown
    id: Client
    attributes:
      label: Client
      description: Country
      options:
        - ID
        - MY
      default: 0
    validations:
      required: true      
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge   
  - type: dropdown
    id: "ios-or-android"
    attributes:
      label: ios or android?
      multiple: true
      options:
        - ios
        - android
  - type: input
    id: EpicLink
    attributes:
      label: Epic Link
      description: Epic Link
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: What happened and what did you expect to happen?
      placeholder: 
      value: "What happened and what did you expect to happen?"
    validations:
      required: true
  - type: textarea
    id: RCA
    attributes:
      label: RCA
      description: Update the RCA
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
