name: 2. Create a Bug
description: Bug/Incident
title: "[Defect]: "
labels: ["bug", "incident"]
body:
  - type: markdown
    attributes:
      value: |
       This is a story
  - type: dropdown
    id: Type
    attributes:
      label: Type
      description: Type
      options:
        - "Bug"
        - "Incident"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: "Phase-Detected"
    attributes:
      label: "phase-detected"
      description: "phase-detected"
      options:
        - "SIT"
        - "UAT"
      default: 0
    validations:
      required: true
  - type: textarea
    id: AffectedVersion
    attributes:
      label: AffectedVersion
      description: Affected Version
      placeholder: 
      value: Affected Version
    validations:
      required: false      
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: What happened and what did you expect to happen?
      placeholder: 
      value: "What happened and what did you expect to happen?"
    validations:
      required: true
  - type: textarea
    id: Steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to Reproduce
      placeholder: 
      value: "Step1:"
    validations:
      required: true
  - type: dropdown
    id: Defect-Category
    attributes:
      label: Defect-category
      description: Defect Category
      options:
        - configuration
        - code
        - environment
      default: 0
    validations:
      required: false
  - type: textarea
    id: RCA
    attributes:
      label: RCA
      description: Update the RCA
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: fix-details
    attributes:
      label: "Fix Details"
      description: fix details?
      placeholder: 
      value: "fix details?"
    validations:
      required: false
  - type: dropdown
    id: Partner
    attributes:
      label: Partner
      description: What environment was the defect detected?
      options:
        - Buka
        - Sociolla
        - TNGD
      default: 0
    validations:
      required: true      

