: blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: User-Story11
    uses: .github/ISSUE_TEMPLATE/user-story-template.yml
    about: Create A User Story.
    - name: Bug-Report
    uses: .github/ISSUE_TEMPLATE/Bug-report.yml
    about: Create A Bug Report.
  
