blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: User-Story11
    url: https://github.com/AASH08/repo300122/blob/53c447d53402ccd2f6a4e396ceb0927b683f64e6/.github/ISSUE_TEMPLATE/user-story-template.yml
    about: Create A User Story.
