name: Create a Design Request
description: "Design Request"
title: "[Design Request]: "
labels: ["Design Request"]
body:
body:
  - type: markdown
    attributes:
      value: |
       This is a Design Request
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: Description
      placeholder: 
      value: "As a <Persona>, I want to <>, so that <>"
    validations:
      required: false
  - type: textarea
    id: Acceptance-Criteria
    attributes:
      label: Acceptance Criteria
      description: Also, tell us, what did you expect to happen?
      placeholder: Tell us what you see !
      value: "Scenario:
      
              Given:
              
              When:
              
              Then:
              
              "
    validations:
      required: false
  - type: checkboxes
    id: Tasks
    attributes:
      label: Tasks
      description: What environment was the defect detected?
      options:
        - label: Figma Links
        - label: Translation
        - label: Approval from country/partner
        - label: Attach Evidence
    validations:
      required: true      
