
name: User Story
about: Create a user story issue

title: User Story
labels:
  - user-story

body:
  - type: markdown
    attributes:
      value: |
        ### User Story
        
        **As a** [user role],
        **I want** [a feature],
        **So that** [benefit or reason].
        
        ### Description
        [Add a detailed description of the user story here]

        ### Acceptance Criteria
        - [List acceptance criteria here]
        - [Each criterion should be clear and measurable]
