name: User Story
description: Create User Story using this template
title: "[US]"


body:
- type: textarea
  attributes:
    label: "Description"


- type: textarea
  attributes:
    label: "Acceptance Criteria"

-type: dropdown
id: Component
attributes:
label:Components
description: changing component
options: 
- configuration
- requirement
- technical
