name: User Story
on: [issue]

jobs:
  user_story:
    steps:
    -name: Create User Story
    run: |
         echo "User Story: ${{github.even.issue.title }}"
         echo "Description: ${{github.event.issue.body }}"
