name: Create a User Story
description: User Story
title: "[Summary]: "
labels: ["Story"]
projects: ["Group1"]
assignees:
  - AASH08
body:
  - type: markdown
    attributes:
      value: |
        Please fill in the requirement in BDD format.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: Acceptance Criteria
    attributes:
      label: Acceptance Criteria
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Team
      description: Team
      options:
        - nexus Avengers
        - nexus Guardians
        - nexus Marvels
        - nexus Excalibur
        - nexus Thunderbolts

      
  - type: dropdown
    id: Components
    attributes:
      label: Components
      multiple: true
      options:
        - Requirement
        - Technical
        - Configuration
        
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
